### ISSUE TITLE
Null passed to loadUrl function causes failed assertion 'url != null': is not true

### ISSUE THREAD

**Issue by hnnngwdlch** [entronad/flutter_echarts#41]
When the EChart widget is disposed (e.g. because the current screen is being popped), the following error is thrown: 

E/flutter (10195): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:webview_flutter/webview_flutter.dart': Failed assertion: line 546 pos 12: 'url != null': is not true.
E/flutter (10195): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
E/flutter (10195): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
E/flutter (10195): #2      WebViewController.loadUrl 
package:webview_flutter/webview_flutter.dart:546
E/flutter (10195): #3      _EchartsState.dispose 

This error is thrown because the loadUrl function does not accept null as an argument:

`  Future<void> loadUrl(
    String url, {
    Map<String, String> headers,
  }) async {
    **assert(url != null);**
    _validateUrlString(url);
    return _webViewPlatformController.loadUrl(url, headers);
  }`

But null is passed to it here:

`  // --- FIX_IOS_LEAK ---
  @override
  void dispose() {
    super.dispose();
    _controller.loadUrl(null).then((_) {
      _controller.clearCache();
    });
  }
  // --- FIX_IOS_LEAK ---`

**Comment by marcmacias96** [comment]
Changing tabs on the navbar redraws the graph, causing performance problems

**Comment by JErazo7** [comment]
> Cambiar las pestañas en la barra de navegación redibuja el gráfico, causando problemas de rendimiento

Same problem

**Comment by entronad** [comment]
@marcmacias96 
@JErazo7 

If the route is changed and the page is recreated, the chart will recreate and redraw.

**Comment by entronad** [comment]
@hnnngwdlch 
Fixed it in 1.3.3
Please upgrade and have a try

**Comment by hnnngwdlch** [comment]
Thanks for the quick response. When an empty string is passed to the loadUrl function, another error occurs while validating the url:

E/flutter ( 8446): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Missing scheme in URL string: ""
E/flutter ( 8446): #0      _validateUrlString 
package:webview_flutter/webview_flutter.dart:733
E/flutter ( 8446): #1      WebViewController.loadUrl 
package:webview_flutter/webview_flutter.dart:547
E/flutter ( 8446): #2      _EchartsState.dispose 

This is the validation method from the WebView implementation, which is triggered by the loadUrl function. The ArgumentError is thrown because of the empty string:

`void _validateUrlString(String url) {
  try {
    final Uri uri = Uri.parse(url);
    if (uri.scheme.isEmpty) {
      throw ArgumentError('Missing scheme in URL string: "$url"');
    }
  } on FormatException catch (e) {
    throw ArgumentError(e);
  }
}`

I think you could prevent this issue by passing a valid url like 'data:,':

`  @override
  void dispose() {
    super.dispose();
    _controller.loadUrl('data:,').then((_) {
      _controller.clearCache();
    });
  }`

Or couldn't you just simply call:

`  @override
  void dispose() {
    super.dispose();
    _controller.clearCache();
  }`

?

**Comment by entronad** [comment]
@hnnngwdlch 

I always tried to load an empty url before clearCache because I read an article saying that this would reduce the memory usage.
The article is about Android WebView and this method seemes not encouraged in Flutter.
I didn't pay much attention on these exception warnings for they won't break the programme. But anyhow, an exception is an exception. Thanks for reminding me of them.
So I removed the loadUrl function in the newest version 3.1.4

**Comment by hnnngwdlch** [comment]
Thanks for your help. Unfortunately, this leads us to the next error message:

```
E/flutter (23640): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method clearCache on channel plugins.flutter.io/webview_0)
E/flutter (23640): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
E/flutter (23640): <asynchronous suspension>
E/flutter (23640): #1      MethodChannelWebViewPlatform.clearCache 
package:webview_flutter/src/webview_method_channel.dart:101
E/flutter (23640): #2      WebViewController.clearCache 
package:webview_flutter/webview_flutter.dart:608
E/flutter (23640): #3      _EchartsState.dispose 
```

This, however, seems to be a general issue with running webViewController.clearCache() on Android that is currently not resolved. See: [https://github.com/flutter/flutter/issues/53122](url)

**Comment by entronad** [comment]
@hnnngwdlch 

It realy broken...
It looks like that the prev issues of loadUrl protected the app from the clearCache issue witch is more serious...
Anyway this time I fixed it with a ugily way (1.3.5). it seems to be fixed at last and I have tested on both platform.
